In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
print(tf.__version__)
df = pd.read_json('../data/output.json').replace(np.nan, 0)
df

2.17.0


contestId index                        name  points  rating  timeLimit  \
0       1870     B             Friendly Arrays     750    1200          2   
1       1870     A             MEXanized Array     500     800          1   
2       1869     B                2D Traveling     750    1100          1   
3       1869     A                Make It Zero     500     900          1   
4       1868     F                        LIS?    3000    3500          5   
5       1868     E                 Min-Sum-Max    2500    3500          5   
6       1868     D      Flower-like Pseudotree    1750    3000          3   
7       1868     C                 Travel Plan    1000    2400          2   
8       1868    B2  Candy Party (Hard Version)     750    2100          2   
9       1868    B1  Candy Party (Easy Version)     500    1700          2   

   memoryLimit                                          statement  \
0          256  You are given two arrays of integers a1 ldots ...   
1          256  You are given three nonnegative integers n k a...   
2          256  Piggy lives on an infinite plane with the Cart...   
3          256  During Zhongkao examination Reycloer met an in...   
4         1024  Entering senior high school life Tom is attrac...   
5         1024  Tom is waiting for his results of Zhongkao exa...   
6          512  A pseudotree is a connected graph which has ex...   
7          512  During the summer vacation after Zhongkao exam...   
8          256  This is the hard version of the problem The on...   
9          256  This is the easy version of the problem The on...   

   tags.bitmasks  tags.greedy  ...  tags.constructive algorithms  \
0            1.0          1.0  ...                           0.0   
1            0.0          1.0  ...                           1.0   
2            0.0          0.0  ...                           0.0   
3            0.0          0.0  ...                           1.0   
4            0.0          1.0  ...                           0.0   
5            0.0          1.0  ...                           1.0   
6            0.0          1.0  ...                           1.0   
7            0.0          0.0  ...                           0.0   
8            1.0          1.0  ...                           1.0   
9            1.0          1.0  ...                           1.0   

   tags.geometry  tags.shortest paths  tags.sortings  tags.data structures  \
0            0.0                  0.0            0.0                   0.0   
1            0.0                  0.0            0.0                   0.0   
2            1.0                  1.0            1.0                   0.0   
3            0.0                  0.0            0.0                   0.0   
4            0.0                  0.0            0.0                   1.0   
5            0.0                  0.0            0.0                   0.0   
6            0.0                  0.0            0.0                   0.0   
7            0.0                  0.0            0.0                   0.0   
8            0.0                  0.0            0.0                   0.0   
9            0.0                  0.0            0.0                   0.0   

   tags.implementation  tags.dp  tags.graphs  tags.trees  tags.combinatorics  
0                  0.0      0.0          0.0         0.0                 0.0  
1                  0.0      0.0          0.0         0.0                 0.0  
2                  0.0      0.0          0.0         0.0                 0.0  
3                  0.0      0.0          0.0         0.0                 0.0  
4                  1.0      0.0          0.0         0.0                 0.0  
5                  0.0      1.0          0.0         0.0                 0.0  
6                  1.0      0.0          1.0         1.0                 0.0  
7                  1.0      1.0          0.0         1.0                 1.0  
8                  1.0      1.0          0.0         0.0                 0.0

In [2]:
# Get all columns that start with 'tags.'
tag_columns = [col for col in df.columns if col.startswith('tags.')]
print('tag_columns:', tag_columns)
print('tag_columns count:', len(tag_columns))
# Get the dataframe data in those columns
tags_df = df[tag_columns]
tags_df

tag_columns: ['tags.bitmasks', 'tags.greedy', 'tags.math', 'tags.constructive algorithms', 'tags.geometry', 'tags.shortest paths', 'tags.sortings', 'tags.data structures', 'tags.implementation', 'tags.dp', 'tags.graphs', 'tags.trees', 'tags.combinatorics']
tag_columns count: 13


tags.bitmasks  tags.greedy  tags.math  tags.constructive algorithms  \
0            1.0          1.0        1.0                           0.0   
1            0.0          1.0        1.0                           1.0   
2            0.0          0.0        1.0                           0.0   
3            0.0          0.0        0.0                           1.0   
4            0.0          1.0        0.0                           0.0   
5            0.0          1.0        0.0                           1.0   
6            0.0          1.0        0.0                           1.0   
7            0.0          0.0        1.0                           0.0   
8            1.0          1.0        1.0                           1.0   
9            1.0          1.0        1.0                           1.0   

   tags.geometry  tags.shortest paths  tags.sortings  tags.data structures  \
0            0.0                  0.0            0.0                   0.0   
1            0.0                  0.0            0.0                   0.0   
2            1.0                  1.0            1.0                   0.0   
3            0.0                  0.0            0.0                   0.0   
4            0.0                  0.0            0.0                   1.0   
5            0.0                  0.0            0.0                   0.0   
6            0.0                  0.0            0.0                   0.0   
7            0.0                  0.0            0.0                   0.0   
8            0.0                  0.0            0.0                   0.0   
9            0.0                  0.0            0.0                   0.0   

   tags.implementation  tags.dp  tags.graphs  tags.trees  tags.combinatorics  
0                  0.0      0.0          0.0         0.0                 0.0  
1                  0.0      0.0          0.0         0.0                 0.0  
2                  0.0      0.0          0.0         0.0                 0.0  
3                  0.0      0.0          0.0         0.0                 0.0  
4                  1.0      0.0          0.0         0.0                 0.0  
5                  0.0      1.0          0.0         0.0                 0.0  
6                  1.0      0.0          1.0         1.0                 0.0  
7                  1.0      1.0          0.0         1.0                 1.0  
8                  1.0      1.0          0.0         0.0                 0.0  
9                  1.0      0.0          1.0         0.0                 0.0

In [3]:
y_data = tags_df.values
y_data

array([[1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.]])

In [4]:
y_data.shape

(10, 13)

In [5]:
wordbag = set()
statements = df['statement'].apply(str.lower)

for st in statements:
    wordbag.update(set(st.split()))
len(wordbag)

542

In [6]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

word2idx = {word: i + 1 for i, word in enumerate(wordbag)}

x_data = [[word2idx[word] for word in st.split()] for st in statements]

x_data = pad_sequences(x_data, padding='post')
x_data

array([[225, 489, 204, ...,   0,   0,   0],
       [225, 489, 204, ...,   0,   0,   0],
       [402,   9, 438, ..., 523, 414, 533],
       ...,
       [113, 313, 103, ...,   0,   0,   0],
       [342, 414, 313, ...,   0,   0,   0],
       [342, 414, 313, ...,   0,   0,   0]])

In [7]:
x_data.shape

(10, 445)

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, SimpleRNN, Dropout, GRU

output_size = y_data.shape[1]
embedding_size = 100

model = Sequential()
model.add(Embedding(len(wordbag)+1, embedding_size, input_shape=(x_data.shape[1],)))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(64, return_sequences=True))
model.add(SimpleRNN(128))
# model.add(Dropout(0.2))
model.add(Dense(64))
model.add(Dense(output_size, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam', metrics=['accuracy'])
model.summary()

c:\Users\enriq\Documents\MyDocuments\University\S8\RedesNeuronales\finalProject\cp-problem-classifier\training\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (None, 445, 100)       │        54,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_10 (SimpleRNN)       │ (None, 445, 32)        │         4,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_11 (SimpleRNN)       │ (None, 445, 64)        │         6,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_12 (SimpleRNN)       │ (None, 128)            │        24,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 13)             │           845 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 98,569 (385.04 KB)

 Trainable params: 98,569 (385.04 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
history=model.fit(x_data,y_data,epochs=100,verbose=2)

Epoch 1/100
1/1 - 5s - 5s/step - accuracy: 0.1000 - loss: 0.7626
Epoch 2/100
1/1 - 0s - 283ms/step - accuracy: 0.0000e+00 - loss: 0.5839
Epoch 3/100
1/1 - 0s - 251ms/step - accuracy: 0.3000 - loss: 0.5219
Epoch 4/100
1/1 - 0s - 301ms/step - accuracy: 0.6000 - loss: 0.4900
Epoch 5/100
1/1 - 0s - 246ms/step - accuracy: 0.5000 - loss: 0.4583
Epoch 6/100
1/1 - 0s - 267ms/step - accuracy: 0.5000 - loss: 0.4260
Epoch 7/100
1/1 - 0s - 300ms/step - accuracy: 0.5000 - loss: 0.3988
Epoch 8/100
1/1 - 0s - 278ms/step - accuracy: 0.4000 - loss: 0.3750
Epoch 9/100
1/1 - 0s - 336ms/step - accuracy: 0.5000 - loss: 0.3539
Epoch 10/100
1/1 - 0s - 301ms/step - accuracy: 0.4000 - loss: 0.3327
Epoch 11/100
1/1 - 0s - 280ms/step - accuracy: 0.4000 - loss: 0.3102
Epoch 12/100
1/1 - 0s - 320ms/step - accuracy: 0.5000 - loss: 0.3049
Epoch 13/100
1/1 - 0s - 283ms/step - accuracy: 0.5000 - loss: 0.2827
Epoch 14/100
1/1 - 0s - 265ms/step - accuracy: 0.5000 - loss: 0.2728
Epoch 15/100
1/1 - 0s - 296ms/step - accur

In [23]:
model.predict(x_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 547ms/step


array([[9.8864537e-01, 9.9887210e-01, 9.9992037e-01, 1.0456267e-02,
        5.8182278e-03, 1.9357317e-03, 5.4402705e-03, 7.9414304e-03,
        1.0003773e-02, 4.8679351e-03, 1.7849198e-03, 2.0568811e-03,
        2.5759584e-03],
       [6.7329048e-03, 9.9616188e-01, 9.9222845e-01, 9.9124938e-01,
        3.8349410e-04, 8.1092492e-04, 1.5815278e-03, 1.6687335e-04,
        2.5675555e-03, 4.8484802e-03, 4.7746142e-03, 3.7506246e-04,
        6.8892565e-05],
       [1.3613079e-03, 2.3299381e-03, 9.9950898e-01, 4.8352112e-03,
        9.9489778e-01, 9.9718910e-01, 9.9549943e-01, 8.6213946e-03,
        4.0372353e-04, 2.8268546e-03, 1.5809203e-03, 3.1723056e-03,
        8.3863912e-03],
       [4.3342275e-06, 1.3000191e-02, 5.9715863e-03, 9.9130952e-01,
        1.1673276e-03, 2.7138663e-03, 2.0450989e-03, 8.2843471e-03,
        4.0796972e-03, 8.6372532e-03, 2.5831405e-03, 6.0134837e-03,
        2.7304019e-03],
       [8.4176604e-03, 9.9385768e-01, 8.0026017e-04, 9.2540290e-03,
        1.9244518e-0